### GET / route

GET http://localhost:3000
Content-Type: application/json


### GET users
GET http://localhost:3000/users
Content-Type: application/json

### GET steps
GET http://localhost:3000/steps
Content-Type: application/json


### GET step x
GET http://localhost:3000/steps/4
Content-Type: application/json


### POST steps
POST http://localhost:3000/steps
Content-Type: application/json

{
    "date" : "1994-03-11",
    "count" : "4323"
}


### GET users/x
GET http://localhost:3000/users/1
Content-Type: application/json


### POST new user   
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Aladár",
    "email": "ALDR@email.com",
    "password": "nemTitkos"
}   


### DELETE user by id
DELETE http://localhost:3000/users/0
Content-Type: application/json


### PATCH
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Anna",
    "age" : 16,
    "gender" : "female"
}   

### POST login

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "admin",
    "password" : "admin"
}
